### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by skinnynpale** [madnessJs/rangeSlider#1]
Бро напиши мне пожалуйста в телеграм 8 999 648 07 18

**Comment by madnessJs** [comment]
Ты кто? По какому вопросу?

**Comment by madnessJs** [comment]
> Бро напиши мне пожалуйста в телеграм 8 999 648 07 18
Ты кто? По какому вопросу?

**Comment by skinnynpale** [comment]
> > Бро напиши мне пожалуйста в телеграм 8 999 648 07 18
> > Ты кто? По какому вопросу?

Я тоже прохожу 2 задание и хотел бы пообщаться

**Comment by madnessJs** [comment]
> > > Бро напиши мне пожалуйста в телеграм 8 999 648 07 18
> > > Ты кто? По какому вопросу?
> 
> Я тоже прохожу 2 задание и хотел бы пообщаться

Так я есть в каналах в телеграмме
